### ISSUE TITLE
Add Learnfactory Tech Hub in Aba

### ISSUE THREAD

**Issue by koolamusic** [unicodeveloper/tech-hubs#29]
Update the list of tech hubs in Abia State 
* [Learnfactory](http://learnfactory.com.ng)
44b, Aba-Owerri Road, Aba, Abia State

**Comment by dexiouz** [comment]
LearnFactory is a leading tech hub in Aba Abia State. 
See techpoint review https://techpoint.africa/2017/12/06/learnfactory-aba-feature/

**Comment by unicodeveloper** [comment]
Please send a PR @koolamusic
