### ISSUE TITLE
Add Alpha HUB kaduna

### ISSUE THREAD

**Issue by syflex** [unicodeveloper/tech-hubs#43]
Name: Alpha HUB.
Address : 31A Botswana Road, Barnawa, Kaduna.
Description :  Alpha Hub is a leading technology services provider delivering business solutions to its clients. The company offers a comprehensive spectrum of IT solutions.

**Comment by unicodeveloper** [comment]
Please send a PR @syflex

**Comment by Harithmetic1** [comment]
Hi, I would love to contribute to this.

**Comment by Harithmetic1** [comment]
I used a blog article I found online about Alpha Hub instead since I could not find a website for Alpha Hub.
